action:
  - PosAttack   # Trooper
  - SPosAttack  # Sargeant
  - VileAttack  # Archvile
  - SkelMissile # Revenant
  - FatAttack1  # Mancubus (1)
  - FatAttack2  # Mancubus (2)
  - FatAttack3  # Mancusub (3)
  - CPosAttack  # Chaingunner
  - TroopAttack # Imp
  - SargAttack  # Demon
  - HeadAttack  # Cacodemon
  - BruisAttack # Baron
  - SkullAttack # Lost Soul
  - BspiAttack  # Arachnotron
  - CyberAttack # Cyberdemon
  - PainAttack  # Pain Elemental

frame:
  - 185 # Trooper
  - 218 # Sargeant
  - 264 # Archvile
  - 341 # Revenant
  - 377 # Mancubus (1)
  - 380 # Mancubus (2)
  - 383 # Mancusub (3)
  - 417 # Chaingunner (1)
  - 418 # Chaingunner (2)
  - 454 # Imp
  - 487 # Demon
  - 506 # Cacodemon
  - 539 # Baron
  - 568 # Hell Knight
  - 590 # Lost Soul
  - 616 # Mastermind (1)
  - 617 # Mastermind (2)
  - 648 # Arachnotron
  - 685 # Cyberdemon (1)
  - 687 # Cyberdemon (2)
  - 689 # Cyberdemon (3)
  - 711 # Pain Elemental
  - 738 # SS (1)
  - 740 # SS (2)

exclusions:
  218:
    - SkullAttack
  264:
    - SkullAttack
  341:
    - SkullAttack
  377:
    - SkullAttack
  380:
    - SkullAttack
  383:
    - SkullAttack
  417:
    - SkullAttack
  418:
    - SkullAttack
  454:
    - SkullAttack
  506:
    - SkullAttack
  539:
    - SkullAttack
  568:
    - SkullAttack
  648:
    - SkullAttack
  685:
    - SkullAttack
  687:
    - SkullAttack
  689:
    - SkullAttack
  711:
    - SkullAttack
  738:
    - SkullAttack
  740:
    - SkullAttack
